# Generated by Django 6.0.6 on 2026-06-23 13:30

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImages', models.JSONField()),
                ('image_id', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'Slider_Table',
                'indexes': [models.Index(fields=['image_id'], name='image_id_idx')],
            },
        ),
    ]
