# Generated by Django 6.0.6 on 2026-06-21 16:36

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('category_img', models.URLField()),
                ('thumbnail_mobile', models.URLField()),
                ('thumbnail_desktop', models.URLField()),
            ],
            options={
                'db_table': 'Product_Category_Table',
                'indexes': [models.Index(fields=['category_id'], name='Product_Cat_categor_e21e41_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategoryModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.BigIntegerField()),
                ('name', models.CharField(help_text="e.g. 'PAC/IPC', 'PLC', 'IO'.", max_length=255)),
                ('description', models.TextField(help_text='Longer descriptive text shown on the SubCategory listing page.')),
                ('category_img', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Products.productcategorymodel')),
            ],
            options={
                'db_table': 'Product_SubCategory_Table',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Q series', 'V100 series'.", max_length=255)),
                ('tag_id', models.BigIntegerField()),
                ('thumbnail_mobile', models.URLField(help_text="Mobile-cropped thumbnail, same rationale as Category's mobile/desktop split.")),
                ('thumbnail_desktop', models.URLField(help_text="Desktop-cropped thumbnail, same rationale as Category's mobile/desktop split.")),
                ('subcategory', models.ForeignKey(help_text='CASCADE: a Tag has no meaning without its parent SubCategory.', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Products.productsubcategorymodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Short line under the product title, e.g. "Powerful performance, flexible expansion..."', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Main descriptive body text for the product detail page.')),
                ('product_img', models.URLField(help_text='Primary image for the product detail page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(help_text='PROTECT, not CASCADE: unlike the levels above it, deleting a Tag that still has live products attached should fail loudly rather than silently deleting product records. Products are the actual sellable/documented items - losing them as a side effect of reorganizing the category chain is the kind of mistake PROTECT exists to catch.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.tagmodel')),
            ],
            options={
                'db_table': 'Product_Table',
                'ordering': ['-name'],
            },
        ),
        migrations.AddIndex(
            model_name='productsubcategorymodel',
            index=models.Index(fields=['subcategory_id'], name='Product_Sub_subcate_a2831f_idx'),
        ),
        migrations.AddIndex(
            model_name='tagmodel',
            index=models.Index(fields=['tag_id'], name='Products_ta_tag_id_4cdcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['product_id'], name='Product_Tab_product_b80843_idx'),
        ),
    ]
