# Generated by Django 6.0.6 on 2026-06-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='Product_Cat_categor_e21e41_idx',
            old_name='product_category_id_idx',
        ),
    ]
