# Generated by Django 6.0.6 on 2026-06-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='thumbnail_desktop',
        ),
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='thumbnail_mobile',
        ),
        migrations.RemoveField(
            model_name='tagmodel',
            name='thumbnail_desktop',
        ),
        migrations.RemoveField(
            model_name='tagmodel',
            name='thumbnail_mobile',
        ),
    ]
