# Generated by Django 6.0.6 on 2026-06-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tagmodel',
            new_name='product_tag_idx',
            old_name='Products_ta_tag_id_4cdcbb_idx',
        ),
        migrations.AlterModelTable(
            name='tagmodel',
            table='Product_Tag_Table',
        ),
    ]
