# Generated by Django 6.0.6 on 2026-06-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_productcategorymodel_thumbnail_desktop_and_more'),
        ('Products', '0002_rename_products_ta_tag_id_4cdcbb_idx_product_tag_idx_and_more'),
    ]

    operations = [
    ]
