# Generated by Django 6.0.6 on 2026-06-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_product_category_id_idx_product_cat_categor_e21e41_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ProductSubCategory',
            new_name='ProductSubCategoryModel',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='Products_pr_tag_id_050c4b_idx',
            old_name='Products_pr_tag_id_846270_idx',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='Products_pr_product_8d4014_idx',
            old_name='Products_pr_product_0df7f3_idx',
        ),
        migrations.RenameIndex(
            model_name='tagmodel',
            new_name='Products_ta_subcate_562758_idx',
            old_name='Products_ta_subcate_0884fe_idx',
        ),
        migrations.RenameIndex(
            model_name='tagmodel',
            new_name='Products_ta_tag_id_4cdcbb_idx',
            old_name='Products_ta_tag_id_b9e449_idx',
        ),
    ]
