# Generated by Django 6.0.6 on 2026-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_merge_20260624_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='specifications',
            field=models.JSONField(default=list),
        ),
    ]
