# Generated by Django 6.0.6 on 2026-06-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_merge_20260624_2312'),
        ('Products', '0004_productmodel_specifications'),
    ]

    operations = [
    ]
