# Generated by Django 6.0.6 on 2026-06-24 11:12

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('resource_url', models.URLField()),
                ('resource_type', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.productcategorymodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.productmodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.productsubcategorymodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='Products.tagmodel')),
            ],
            options={
                'db_table': 'Download_Table',
                'indexes': [models.Index(fields=['download_id'], name='download_id_idx')],
            },
        ),
    ]
