# Generated by Django 6.0.6 on 2026-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadmodel',
            name='resource_type',
            field=models.CharField(default='CATALOG', max_length=50),
        ),
    ]
