# Generated by Django 6.0.6 on 2026-06-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0001_initial'),
        ('Products', '0002_rename_products_ta_tag_id_4cdcbb_idx_product_tag_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Products.productcategorymodel'),
        ),
        migrations.AlterField(
            model_name='downloadmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.productmodel'),
        ),
        migrations.AlterField(
            model_name='downloadmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='Products.productsubcategorymodel'),
        ),
        migrations.AlterField(
            model_name='downloadmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='Products.tagmodel'),
        ),
    ]
