# Generated by Django 6.0.6 on 2026-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0002_alter_downloadmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='downloadmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='downloadmodel',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='downloadmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='downloadmodel',
            name='category_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadmodel',
            name='product_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadmodel',
            name='subcategory_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadmodel',
            name='tag_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
