# Generated by Django 6.0.6 on 2026-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0002_downloadmodel_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadmodel',
            name='resource_type',
            field=models.CharField(max_length=50),
        ),
    ]
