# Generated by Django 6.0.6 on 2026-06-24 19:38

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmissionModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('poul', models.CharField(blank=True, help_text='Poul details', max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('product_of_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('form_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'Contact_Submission_Table',
                'ordering': ['-created_at'],
            },
        ),
    ]
