# Generated by Django 6.0.6 on 2026-06-19 10:18

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
            ],
            options={
                'db_table': 'Solutions_Category_Table',
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='Solutions.solutionscategory')),
            ],
            options={
                'db_table': 'Solutions_Table',
            },
        ),
    ]
