# Generated by Django 6.0.6 on 2026-06-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionsCategory',
            new_name='SolutionsCategoryModel',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='SolutionsModel',
        ),
    ]
