# Generated by Django 6.0.6 on 2026-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0002_rename_solutionscategory_solutionscategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionsmodel',
            name='videoUrl',
            field=models.URLField(default='https://example.com/fix.jps'),
        ),
    ]
