# Generated by Django 6.0.6 on 2026-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0003_solutionsmodel_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionsmodel',
            name='videoUrl',
            field=models.URLField(),
        ),
    ]
