# Generated by Django 6.0.6 on 2026-06-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0004_alter_solutionsmodel_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='Solutions.solutionscategorymodel'),
        ),
    ]
