# Generated by Django 6.0.6 on 2026-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0005_alter_solutionsmodel_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solutionscategorymodel',
            index=models.Index(fields=['category_name'], name='category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionscategorymodel',
            index=models.Index(fields=['category_id'], name='category_id_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionsmodel',
            index=models.Index(fields=['solutions_id'], name='solutions_id_idx'),
        ),
    ]
