# Generated by Django 6.0.6 on 2026-06-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoranalytics',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
