# Generated by Django 6.0.6 on 2026-06-18 06:55

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('heading', models.CharField(max_length=500)),
                ('thumbnail', models.URLField()),
            ],
            options={
                'db_table': 'News_Table',
            },
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_content', models.JSONField(default=list)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='News.newsmodel')),
            ],
            options={
                'db_table': 'News_Content_Table',
                'unique_together': {('news', 'news_content')},
            },
        ),
    ]
