# Generated by Django 6.0.6 on 2026-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newscontent',
            unique_together=set(),
        ),
    ]
