# Generated by Django 6.0.6 on 2026-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_newscontent_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsmodel',
            index=models.Index(fields=['news_id'], name='news_id_idx'),
        ),
    ]
