# Generated by Django 6.0.6 on 2026-06-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_customer_pixsysadminmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerModel',
        ),
    ]
