# Generated by Django 6.0.6 on 2026-06-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_rename_customer_customermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='PixsysCustomerModel',
        ),
        migrations.AlterModelTable(
            name='pixsysadminmodel',
            table='Pixsys_Admin_Table',
        ),
        migrations.AlterModelTable(
            name='pixsyscustomermodel',
            table='Pixsys_Customer_Table',
        ),
    ]
