# Generated by Django 6.0.6 on 2026-06-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_rename_customermodel_pixsyscustomermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixsyscustomermodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
