# Generated by Django 6.0.6 on 2026-06-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_pixsyscustomermodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pixsysadminmodel',
            options={'verbose_name': 'Pixsys Admin'},
        ),
        migrations.AlterModelOptions(
            name='pixsyscustomermodel',
            options={'verbose_name': 'Pixsys Admin'},
        ),
    ]
