# Generated by Django 6.0.6 on 2026-06-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_alter_pixsysadminmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pixsyscustomermodel',
            options={'verbose_name': 'Pixsys Customer'},
        ),
    ]
