# Generated by Django 6.0.6 on 2026-06-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_pixsyscustomermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Shivvilon Solution Admin'},
        ),
    ]
