# Generated by Django 6.0.6 on 2026-07-23 06:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixsyscustomermodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerOTPModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_data', to='Auth.pixsyscustomermodel')),
            ],
            options={
                'db_table': 'Pixsys_Customer_OTP',
            },
        ),
    ]
