# Generated by Django 6.0.6 on 2026-07-23 08:02

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_pixsyscustomermodel_is_verified_customerotpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_details', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'db_table': 'Pixsys_Company_Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSMTPConfig',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.EmailField(blank=True, help_text='The email address used to send emails.', max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text='The App Password for the email.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'System SMTP Configuration',
                'db_table': 'Pixsys_System_SMTP_Config',
            },
        ),
    ]
