# Generated by Django 6.0.6 on 2026-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_companysettings_systemsmtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerotpmodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
