# Generated by Django 6.0.6 on 2026-07-20 13:59

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.BigIntegerField(unique=True)),
                ('product_id', models.BigIntegerField()),
                ('tag_id', models.BigIntegerField()),
                ('subcategory_id', models.BigIntegerField()),
                ('category_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(help_text='Thumbnail URL for the resource')),
                ('file', models.URLField(help_text='File/Document URL')),
            ],
            options={
                'db_table': 'Product_Resource_Table',
                'indexes': [models.Index(fields=['resource_id'], name='Product_Res_resourc_2330c2_idx'), models.Index(fields=['product_id'], name='Product_Res_product_557a74_idx')],
            },
        ),
    ]
