# Generated by Django 6.0.6 on 2026-07-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemodel',
            old_name='file',
            new_name='resource_url',
        ),
    ]
